stages:
  - install
  - build
  - test
  - deploy

variables:
  NODE_ENV: "development"

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:18
  script:
    - npm ci

build_app:
  stage: build
  image: node:18
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

run_tests:
  stage: test
  image: node:18
  script:
    - npm run test


deploy_app:
  stage: deploy
  image: node:18
  script:
    - npm install -g heroku
    - echo "$HEROKU_API_KEY" | heroku auth:token
    - heroku git:remote -a $HEROKU_APP_NAME
    - git remote -v
    - git config --global user.email "$HEROKU_EMAIL"
    - git config --global user.name "GitLab CI"
    - git add .
    - git commit -m "Deploy from GitLab CI" || echo "No changes to commit"
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
  only:
    - main

